/**
 * The box-score contract shared by BOTH sim engines.
 *
 * The quick-sim and the full-fidelity engine produce the same `GameOutcome`:
 * a final score, how it was decided, the per-player stat line, and a
 * `GameStream` (sparse from quick-sim, dense + positional from full-sim). The
 * career/season layer applies an outcome the same way regardless of which engine
 * produced it — so the user's watched game and the background games stay
 * perfectly consistent.
 */
import type { GameStream, PlayerId, TeamId } from '@domain'

export interface GamePlayerStat {
  playerId: PlayerId
  goals: number
  assists: number
  shots: number
  penaltyMinutes: number
  /** Time on ice, seconds. */
  toi: number
  // Goalie-only; 0 for skaters.
  saves: number
  shotsAgainst: number
  goalsAgainst: number
  // Physical-play counters (default 0; accumulated from event stream).
  hits: number
  blockedShots: number
  takeaways: number
  giveaways: number
  /** On-ice goal differential at even strength / shorthanded (NHL +/- rule —
   *  power-play goals don't count). Skaters only; 0 for goalies. */
  plusMinus: number
  /**
   * Expected goals generated by this player as shooter (xGF contribution).
   * Optional — absent on stats serialized before this field was added;
   * treat missing as 0. Accumulated per shot from the empirical xG surface.
   */
  xg?: number
  /**
   * Expected goals conceded while this player was the goalie on ice (xGA).
   * Optional — absent on pre-xG saves; treat missing as 0.
   */
  xgAgainst?: number
  /**
   * Expected assists: the xG of the shot on a goal where this player was
   * the primary assister. Optional — absent on pre-xG saves; treat missing as 0.
   */
  xA?: number
}

export type DecidedBy = 'regulation' | 'overtime' | 'shootout'

export interface GameOutcome {
  homeTeamId: TeamId
  awayTeamId: TeamId
  homeGoals: number
  awayGoals: number
  decidedBy: DecidedBy
  stream: GameStream
  playerStats: Map<PlayerId, GamePlayerStat>
}

export function emptyStat(playerId: PlayerId): GamePlayerStat {
  return {
    playerId,
    goals: 0,
    assists: 0,
    shots: 0,
    penaltyMinutes: 0,
    toi: 0,
    saves: 0,
    shotsAgainst: 0,
    goalsAgainst: 0,
    hits: 0,
    blockedShots: 0,
    takeaways: 0,
    giveaways: 0,
    plusMinus: 0,
    xg: 0,
    xgAgainst: 0,
    xA: 0,
  }
}

export function mergePlayerStats(
  totals: Map<PlayerId, GamePlayerStat>,
  game: Map<PlayerId, GamePlayerStat>
): void {
  for (const [id, s] of game) {
    let t = totals.get(id)
    if (!t) {
      t = emptyStat(id)
      totals.set(id, t)
    }
    t.goals += s.goals
    t.assists += s.assists
    t.shots += s.shots
    t.penaltyMinutes += s.penaltyMinutes
    t.toi += s.toi
    t.saves += s.saves
    t.shotsAgainst += s.shotsAgainst
    t.goalsAgainst += s.goalsAgainst
    t.hits += s.hits
    t.blockedShots += s.blockedShots
    t.takeaways += s.takeaways
    t.giveaways += s.giveaways
    t.plusMinus += s.plusMinus
    if (s.xg !== undefined) t.xg = (t.xg ?? 0) + s.xg
    if (s.xgAgainst !== undefined) t.xgAgainst = (t.xgAgainst ?? 0) + s.xgAgainst
    if (s.xA !== undefined) t.xA = (t.xA ?? 0) + s.xA
  }
}
