/**
 * `npm run scorecard` — the M0 realism scorecard run (NOT part of `npm test`).
 *
 * Sims N seeded full-fidelity games on the imported real-roster league
 * (mods/nhl-ehm/database.json, read-only, found by walking up from the cwd so a
 * worktree finds the main checkout's mod) or the vanilla generated league,
 * analyzes every stream, aggregates, compares to src/calibrate/matchTargets.json,
 * and writes:
 *   docs/MATCH-SCORECARD.md     human table (metric, ours, NHL, band, pass/fail, trend)
 *   docs/match-scorecard.json   machine copy (rows + shape offsets + shot grids)
 *   .cache/replay/*.html        side-by-side eye-test pages (git-ignored)
 *
 * Env: SCORECARD_GAMES (default 60), SCORECARD_DB (mod path), SCORECARD_VANILLA=1,
 *      REF_TRACKING=<TrackedSequence json> to use real tracking as the reference.
 */
import { it } from 'vitest'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import type { Player, PlayerId, Position } from '@domain'
import { generateLeague } from '@data/generate'
import { loadModDatabase, validateModDatabase } from '@data'
import { fullSimGame } from '@engine/full/fullSim'
import {
  aggregate,
  analyzeGame,
  compare,
  findSituationClip,
  scorecardMarkdown,
  SHAPE_TEMPLATES,
  sideBySideHtml,
  templateSequence,
  trackingToStream,
  type GameMetrics,
  type MatchTargets,
  type TrackedSequence
} from './index'
import rawTargets from '@calibrate/matchTargets.json'

function findModDb(): string | null {
  if (process.env.SCORECARD_VANILLA) return null
  if (process.env.SCORECARD_DB) return existsSync(process.env.SCORECARD_DB) ? process.env.SCORECARD_DB : null
  let dir = resolve(process.cwd())
  for (let i = 0; i < 6; i++) {
    const p = join(dir, 'mods', 'nhl-ehm', 'database.json')
    if (existsSync(p)) return p
    const up = dirname(dir)
    if (up === dir) break
    dir = up
  }
  return null
}

it('realism scorecard', () => {
  const t0 = Date.now()
  const games = Number(process.env.SCORECARD_GAMES ?? 60)
  const dbPath = findModDb()
  const data = dbPath
    ? loadModDatabase(validateModDatabase(JSON.parse(readFileSync(dbPath, 'utf8'))), { seed: 2029 })
    : generateLeague({ seed: 99 })
  const leagueLabel = dbPath ? 'imported real-roster league (mods/nhl-ehm, read-only)' : 'vanilla generated league (seed 99)'
  const resolvePlayer = (id: PlayerId): Player => {
    const p = data.players.get(id)
    if (!p) throw new Error(`unknown player ${id}`)
    return p
  }
  const teams = data.league.teams
  const positions = new Map<string, Position>()
  for (const [id, p] of data.players) positions.set(id, p.position)

  const perGame: GameMetrics[] = []
  let firstStream: ReturnType<typeof fullSimGame>['stream'] | null = null
  let simMs = 0
  let anMs = 0
  for (let i = 0; i < games; i++) {
    const home = data.teams.get(teams[(i * 7) % teams.length])!
    const away = data.teams.get(teams[(i * 7 + 3 + (i % 5)) % teams.length])!
    const s0 = Date.now()
    const out = fullSimGame(home, away, resolvePlayer, { seed: 7000 + i })
    simMs += Date.now() - s0
    const a0 = Date.now()
    perGame.push(analyzeGame(out.stream, { positions, label: `${home.abbreviation ?? home.id} @ ${away.abbreviation ?? away.id}` }))
    anMs += Date.now() - a0
    if (i === 0) firstStream = out.stream
  }
  const dist = aggregate(perGame)
  const targets = rawTargets as unknown as MatchTargets

  const jsonPath = join('docs', 'match-scorecard.json')
  const prev = existsSync(jsonPath) ? (JSON.parse(readFileSync(jsonPath, 'utf8')) as { rows: { id: string; ours: number | null }[] }) : null
  const sc = compare(dist, targets, prev)
  const wallS = (Date.now() - t0) / 1000

  // Shape offsets (mean sim − template per role) — what the lead engine should correct.
  const shapeOffsets = SHAPE_TEMPLATES.map((t) => {
    const acc = dist.shapes[t.id]
    const n = acc?.frames ?? 0
    const avg = (o: { x: number; y: number }) => ({ dx: +(o.x / Math.max(1, n)).toFixed(1), dy: +(o.y / Math.max(1, n)).toFixed(1) })
    return {
      id: t.id,
      frames: n,
      attack: t.attack.map((r, i) => ({ role: r.role, ...(acc ? avg(acc.attackOffsets[i]) : { dx: null, dy: null }) })),
      defend: t.defend.map((r, i) => ({ role: r.role, ...(acc ? avg(acc.defendOffsets[i]) : { dx: null, dy: null }) }))
    }
  })

  const header = `# Match realism scorecard (M0)

Generated by \`npm run scorecard\` (src/engine/analysis/scorecard.harness.test.ts). **Engine:** current full-fidelity director engine (src/engine/full). **League:** ${leagueLabel}. **Sample:** ${games} full games, seeds 7000–${7000 + games - 1}. **Run time:** ${wallS.toFixed(0)} s wall (sim ${(simMs / 1000).toFixed(0)} s, analysis ${(anMs / 1000).toFixed(0)} s).

What this is: the analyzer (src/engine/analysis) reads ONLY the GameEvent stream (events + 4 fps positional frames) and measures skating, team shape, passing direction, entries, shots, physical play, flow, goaltending, motion quality and shape similarity to textbook team systems; each number is graded against a target band from src/calibrate/matchTargets.json. Targets are only as good as their source — the Confidence column says which are measured NHL aggregates and which are estimates or design requirements (docs/MATCH-DATA-SOURCES.md). A metric the stream cannot show yet is listed at the bottom with the additive event field it needs.`
  writeFileSync(join('docs', 'MATCH-SCORECARD.md'), scorecardMarkdown(sc, header, targets.sources) + shapeOffsetsMd(shapeOffsets))
  writeFileSync(
    jsonPath,
    JSON.stringify(
      {
        generated: sc.generated,
        engine: 'full/director',
        league: leagueLabel,
        games,
        runSeconds: +wallS.toFixed(1),
        summary: sc.summary,
        rows: sc.rows.map((r) => ({ id: r.id, group: r.group, ours: r.ours === null ? null : +r.ours.toFixed(5), verdict: r.verdict, band: r.target?.band ?? null, value: r.target?.value ?? null, confidence: r.target?.confidence ?? null, trend: r.trend })),
        shapeOffsets,
        shotGrid: { ours: dist.grids['shot.distAngle'].cells, nhl: targets.shotGrid?.attempts.flat() ?? null, cols: dist.grids['shot.distAngle'].cols },
        heat: { skaters: dist.grids['heat.skaters'], hits: dist.grids['heat.hits'], shots: dist.grids['heat.shots'] }
      },
      null,
      1
    ) + '\n'
  )

  // Eye test: textbook reference vs the sim in the same situation.
  mkdirSync(join('.cache', 'replay'), { recursive: true })
  const refFile = process.env.REF_TRACKING
  const extRef = refFile && existsSync(refFile) ? (JSON.parse(readFileSync(refFile, 'utf8')) as TrackedSequence) : null
  const chains: [string, string[]][] = [
    ['ozLowCycle', ['ozLowCycle', 'ozPointShot', 'ozLowCycle']],
    ['breakoutWall', ['breakoutWall', 'nzRegroup', 'rushEntry']],
    ['pp131', ['pp131']]
  ]
  const pages: string[] = []
  for (const [tid, chain] of chains) {
    const tpl = SHAPE_TEMPLATES.find((t) => t.id === tid)!
    const refSeq = extRef ?? templateSequence(chain, { holdS: 1.5, moveS: 2.5 })
    const refStream = trackingToStream(refSeq)
    const clip = firstStream ? findSituationClip(firstStream, tpl, { beforeS: 2, afterS: 6 }) : null
    if (!clip) continue
    const file = join('.cache', 'replay', `side-by-side-${tid}.html`)
    writeFileSync(
      file,
      sideBySideHtml(
        { title: extRef ? `Reference: ${extRef.id}` : `Textbook: ${chain.join(' → ')}`, subtitle: `${refSeq.source} — ${refSeq.license}`, stream: refStream },
        { title: `Sim: ${tpl.label}`, subtitle: `seed 7000, period ${clip.period}, around t=${clip.atT.toFixed(1)} s`, stream: clip.stream },
        `Eye test — ${tpl.label}`
      )
    )
    writeFileSync(join('.cache', 'replay', `reference-${tid}.stream.json`), JSON.stringify(refStream))
    pages.push(file)
  }

  // eslint-disable-next-line no-console
  console.log(
    `scorecard: ${sc.summary.pass} pass / ${sc.summary.fail} fail / ${sc.summary.info} info / ${sc.summary.na} n/a over ${games} games in ${wallS.toFixed(0)} s (sim ${(simMs / 1000).toFixed(0)} s, analysis ${(anMs / 1000).toFixed(0)} s); eye-test pages: ${pages.join(', ')}`
  )
}, 3_600_000)

function shapeOffsetsMd(rows: { id: string; frames: number; attack: { role: string; dx: number | null; dy: number | null }[]; defend: { role: string; dx: number | null; dy: number | null }[] }[]): string {
  const L: string[] = ['## Shape offsets — where our skaters stand vs the textbook spot', '', 'Mean (sim − template) per role in feet, in the possessing team\'s attack frame (+dx = further up ice toward the net being attacked, +dy = toward the puck-side boards). Templates: src/engine/analysis/shapes.ts.', '']
  for (const r of rows) {
    L.push(`**${r.id}** — ${r.frames} matching frames`, '')
    if (r.frames === 0) {
      L.push('_no matching frames in the sample_', '')
      continue
    }
    L.push('| Team | Role | dx ft | dy ft |', '|---|---|---|---|')
    for (const a of r.attack) L.push(`| possessing | ${a.role} | ${a.dx} | ${a.dy} |`)
    for (const d of r.defend) L.push(`| defending | ${d.role} | ${d.dx} | ${d.dy} |`)
    L.push('')
  }
  return L.join('\n') + '\n'
}
